import '../globals.css';

export const metadata = {
  title: 'Next Sanity App',
  description: 'Generated by Mariia Kovalova',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
