import i18n from '@/i18n.config';
import Header from '@/components/Header/Header';
import Locale from '@/types/Locale';
import '@/app/globals.css';

export const metadata = {
  title: 'Next Sanity App',
  description: 'Generated by Mariia Kovalova',
};

export async function generateStaticParams() {
  return i18n.locales.map(locale => ({ locale: locale }));
}

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: Locale };
}) {
  return (
    <html lang={locale}>
      <body className="mx-auto max-w-7xl px-8 py-10">
        <Header locale={locale} />
        <main className="py-20">{children}</main>
      </body>
    </html>
  );
}
